"""Add cheating

Revision ID: b22a8c788237
Revises: a156ef1b8c8d
Create Date: 2026-03-11 13:24:35.995362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22a8c788237'
down_revision: Union[str, Sequence[str], None] = 'a156ef1b8c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('cheating_detected', sa.Boolean(), nullable=True))
    op.add_column('results', sa.Column('reason_for_stop', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'reason_for_stop')
    op.drop_column('results', 'cheating_detected')
    # ### end Alembic commands ###
