"""add_yakuniy_table

Revision ID: b5d0ae85d0c0
Revises: 11568bf0320c
Create Date: 2026-04-03 22:32:59.324422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d0ae85d0c0'
down_revision: Union[str, Sequence[str], None] = '11568bf0320c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yakuniy',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('quiz_questions_quiz_id_fkey'), 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_questions_quiz_id_fkey'), 'quiz_questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_table('yakuniy')
    # ### end Alembic commands ###
