"""restore_missing_cheating_columns

Revision ID: dfc90e8f944e
Revises: 2766543ead64
Create Date: 2026-04-13 19:52:51.116162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc90e8f944e'
down_revision: Union[str, Sequence[str], None] = '2766543ead64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yakuniy',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hemis_transactions',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('login_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('questions', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('questions_user_id_fkey'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('questions_subject_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('quiz_questions_quiz_id_fkey'), 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quizzes_subject_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_group_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_user_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quizzes', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('results', sa.Column('cheating_detected', sa.Boolean(), nullable=True))
    op.add_column('results', sa.Column('reason_for_stop', sa.String(length=255), nullable=True))
    op.add_column('results', sa.Column('cheating_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'cheating_image_url')
    op.drop_column('results', 'reason_for_stop')
    op.drop_column('results', 'cheating_detected')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_user_id_fkey'), 'quizzes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('quizzes_group_id_fkey'), 'quizzes', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('quizzes_subject_id_fkey'), 'quizzes', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_questions_quiz_id_fkey'), 'quiz_questions', 'quizzes', ['quiz_id'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_subject_id_fkey'), 'questions', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('questions_user_id_fkey'), 'questions', 'users', ['user_id'], ['id'])
    op.alter_column('questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('hemis_transactions')
    op.drop_table('yakuniy')
    # ### end Alembic commands ###
