server {
    listen 80;
    server_name organization.api.nsumt.uz;
    client_max_body_size 20M;

    location ~ ^/(api|uploads|evidence|health|metrics|docs|redoc|openapi\.json|admin) {
        proxy_pass http://backend:8000;
    }

    location / {
        proxy_pass http://frontend:3000;
    }
}

server {
    listen 80;
    server_name organization.face.nsumt.uz;
    client_max_body_size 20M;

    location / {
        proxy_pass http://face-detection:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
