"""Maker saver models

Revision ID: 11568bf0320c
Revises: a156ef1b8c8d
Create Date: 2026-03-27 00:47:09.738527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11568bf0320c'
down_revision: Union[str, Sequence[str], None] = 'a156ef1b8c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('questions_subject_id_fkey'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('questions_user_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'questions', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('quizzes_subject_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_user_id_fkey'), 'quizzes', type_='foreignkey')
    op.drop_constraint(op.f('quizzes_group_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quizzes', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_group_id_fkey'), 'quizzes', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('quizzes_user_id_fkey'), 'quizzes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('quizzes_subject_id_fkey'), 'quizzes', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_user_id_fkey'), 'questions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('questions_subject_id_fkey'), 'questions', 'subjects', ['subject_id'], ['id'])
    op.alter_column('questions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
