"""add_group_id_to_resources

Revision ID: 8b91714a27ed
Revises: 0adbe256bd48
Create Date: 2026-04-27 19:52:29.732310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b91714a27ed'
down_revision: Union[str, Sequence[str], None] = '0adbe256bd48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_resources_group_id'), 'resources', ['group_id'], unique=False)
    op.create_foreign_key(None, 'resources', 'groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_index(op.f('ix_resources_group_id'), table_name='resources')
    op.drop_column('resources', 'group_id')
    # ### end Alembic commands ###
