"""Add attempt to quiz and correct_answer to user_answers

Revision ID: a156ef1b8c8d
Revises: f6010073a06b
Create Date: 2026-02-20 10:08:12.730304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a156ef1b8c8d'
down_revision: Union[str, Sequence[str], None] = 'f6010073a06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('group_teachers_teacher_id_fkey'), 'group_teachers', type_='foreignkey')
    op.create_foreign_key(None, 'group_teachers', 'users', ['teacher_id'], ['id'])
    op.add_column('quizzes', sa.Column('attempt', sa.Integer(), nullable=True))
    op.add_column('user_answers', sa.Column('correct_answer', sa.String(), nullable=True))
    op.alter_column('user_answers', 'answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_answers', 'answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('user_answers', 'correct_answer')
    op.drop_column('quizzes', 'attempt')
    op.drop_constraint(None, 'group_teachers', type_='foreignkey')
    op.create_foreign_key(op.f('group_teachers_teacher_id_fkey'), 'group_teachers', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
