"""your descriptive message here

Revision ID: e9a039fd8295
Revises: 11568bf0320c
Create Date: 2026-04-01 07:15:46.802610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a039fd8295'
down_revision: Union[str, Sequence[str], None] = '11568bf0320c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('quiz_questions_quiz_id_fkey'), 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_questions', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.add_column('results', sa.Column('cheating_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'cheating_image_url')
    op.drop_constraint(None, 'quiz_questions', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_questions_quiz_id_fkey'), 'quiz_questions', 'quizzes', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
